variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/src'
  VERBOSE: 'true'
  REPO_TOKEN: 'HjqgaDfkx6oUp9xhR4mR'

deploy:
  stage: deploy
  image: registry.thecall.dev/akorl/apps-landing-page
  script:
    - echo "App deployed successfully."