before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/src'
  VERBOSE: 'true'
  REPO_TOKEN: 'azure'

deploy:
  stage: deploy
  image: registry.thecall.dev/akorl/apps-landing-page
  script:
    - echo "App deployed successfully."